version: 2
jobs:
  stamp:
    parameters:
      master_branch:
        type: boolean
        default: false
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - unless:
          condition: << parameters.master_branch >>
          steps:
            - run:
                name: Stamp Build on Version
                command: sed -i "s/-dev/-${CIRCLE_BUILD_NUM}/g" package.json
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - persist_to_workspace:
          root: ./
          paths:
            - package.json
            - .npmrc
  publish_develop:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm publish --tag dev --access public
  publish_master:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: npm publish --access public
workflows:
  version: 2
  publish:
    jobs:
      - stamp:
          master_branch: false
          filters:
            branches:
              only: develop
      - stamp:
          master_branch: true
          filters:
            branches:
              only: master
      - publish_develop:
          requires:
            - stamp
          filters:
            branches:
              only: develop
      - publish_master:
          requires:
            - stamp
          filters:
            branches:
              only: master